name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: Laravel latest
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo_sqlite, inotify
          coverage: none
          tools: composer:v2
        env:
          fail-fast: true

      - name: Install dependencies
        run: >-
          composer update
          --with-all-dependencies
          --prefer-stable
          --no-interaction
          --no-progress

      - name: Review
        run: composer review
