name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux native and polling
            extensions: pdo_sqlite, inotify
          - os: macos-latest
            name: macOS polling
            extensions: pdo_sqlite
          - os: windows-latest
            name: Windows polling
            extensions: pdo_sqlite, fileinfo

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: ${{ matrix.extensions }}
          coverage: none
          tools: composer:v2
        env:
          fail-fast: true

      - name: Install dependencies
        run: >-
          composer update
          --with-all-dependencies
          --prefer-stable
          --no-interaction
          --no-progress

      - name: Review
        run: composer review
